version: '3.8'

services:
  back:
    build: ./back
    container_name: back
    hostname: localhost
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"

  front:
    build: ./front
    container_name: front
    hostname: localhost
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - back
