version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: birthday_reminder_db
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
