version: '3.8'

services:
  back:
    build: ./back
    container_name: back
    hostname: localhost
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  front:
    build: ./front
    container_name: front
    hostname: localhost
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - back

  db:
    build: ./db
    container_name: birthday_reminder_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations:/migrations
      - ./db/seed-data:/seed-data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
