name: CI/CD to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd BirthdayReminderV2/

            git pull origin master

            sudo docker-compose stop front back
            sudo docker-compose rm -f front back

            sudo docker rmi $(sudo docker images "birthdayreminderv2-front" -q) || true
            sudo docker rmi $(sudo docker images "birthdayreminderv2-back" -q) || true

            sudo docker-compose build --no-cache front back
            sudo docker-compose up -d front back

            sudo docker-compose exec -T db bash /apply_migrations.sh
